spring:
  application:
    name: ais-auto-repair-shop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ais-auto-repair-shop
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
  cache:
    type: ehcache

server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html